// Package web_test verifies the real cross-package artifact boundary: the
// frontend built by Vite must be embedded and servable by the Go HTTP package.
package web_test

import (
	"io/fs"
	"mime"
	"net/http"
	"net/http/httptest"
	"regexp"
	"strings"
	"testing"

	"github.com/snaraj/naranjo.online/internal/server"
	website "github.com/snaraj/naranjo.online/internal/web"
)

// builtAssetReference finds Vite's content-addressed script and stylesheet URLs
// without coupling the test to hashes that legitimately change on every build.
var builtAssetReference = regexp.MustCompile(`(?:src|href)="(/assets/[^"]+)"`)

// contentHashedAsset protects the one-year immutable-cache promise made by the
// Go server. A future bundler change must not publish mutable names under it.
var contentHashedAsset = regexp.MustCompile(
	`^/assets/(?:[A-Za-z0-9._-]+/)*[A-Za-z0-9._-]+-[A-Za-z0-9_-]{8,}\.[A-Za-z0-9]+$`,
)

// strongETag is the quoted SHA-256 identity generated by serveBytes. Matching
// it across GET and HEAD keeps caches and release probes deterministic.
var strongETag = regexp.MustCompile(`^"[0-9a-f]{64}"$`)

// expectedOriginHeaders is the complete browser-facing policy shared by the
// generated shell and its immutable resources at the production Go boundary.
// HSTS is part of it because every request here is edge-declared TLS (see
// edgeRequest); the proto-conditional emission itself is pinned by the
// server package's policy suite.
var expectedOriginHeaders = map[string]string{
	"Content-Security-Policy":      "default-src 'self'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'; object-src 'none'",
	"Cross-Origin-Resource-Policy": "same-origin",
	"Permissions-Policy":           "camera=(), geolocation=(), microphone=()",
	"Referrer-Policy":              "no-referrer",
	"Strict-Transport-Security":    "max-age=31536000",
	"X-Content-Type-Options":       "nosniff",
	"X-Frame-Options":              "DENY",
}

// edgeRequest builds the request shape every real browser produces at this
// boundary: forwarded by the TLS-terminating edge, which declares the
// visitor's protocol. The full origin header policy — the HSTS promise
// included — must answer it.
func edgeRequest(method, target string) *http.Request {
	request := httptest.NewRequest(method, target, nil)
	request.Header.Set("X-Forwarded-Proto", "https")
	return request
}

// assertServedFile proves that GET and HEAD expose the same immutable identity,
// cache policy, content metadata, and browser-security boundary for one file.
func assertServedFile(t *testing.T, handler http.Handler, publicPath, cacheControl string) {
	t.Helper()

	response := httptest.NewRecorder()
	handler.ServeHTTP(response, edgeRequest(http.MethodGet, publicPath))
	if response.Code != http.StatusOK || response.Body.Len() == 0 {
		t.Errorf("asset %s = status %d, %d bytes", publicPath, response.Code, response.Body.Len())
	}
	if got := response.Header().Get("Content-Type"); got == "" {
		t.Errorf("asset %s has no Content-Type", publicPath)
	}
	if got := response.Header().Get("Cache-Control"); got != cacheControl {
		t.Errorf("asset %s Cache-Control = %q, want %q", publicPath, got, cacheControl)
	}
	if etag := response.Header().Get("ETag"); !strongETag.MatchString(etag) {
		t.Errorf("asset %s ETag = %q", publicPath, etag)
	}
	for name, expected := range expectedOriginHeaders {
		if got := response.Header().Get(name); got != expected {
			t.Errorf("asset %s %s = %q, want %q", publicPath, name, got, expected)
		}
	}

	head := httptest.NewRecorder()
	handler.ServeHTTP(head, edgeRequest(http.MethodHead, publicPath))
	if head.Code != http.StatusOK || head.Body.Len() != 0 {
		t.Errorf("HEAD %s = status %d, %d bytes", publicPath, head.Code, head.Body.Len())
	}
	for _, name := range []string{"Content-Type", "Cache-Control", "ETag"} {
		if head.Header().Get(name) != response.Header().Get(name) {
			t.Errorf("HEAD %s %s does not match GET", publicPath, name)
		}
	}
	for name, expected := range expectedOriginHeaders {
		if got := head.Header().Get(name); got != expected {
			t.Errorf("HEAD %s %s = %q, want %q", publicPath, name, got, expected)
		}
	}
}

// TestBuiltFrontendIsEmbeddedAndServed proves that CI is testing the production
// bundle, its immutable assets, and the exclusion of checkout-only placeholders.
func TestBuiltFrontendIsEmbeddedAndServed(t *testing.T) {
	assets, err := website.FileSystem()
	if err != nil {
		t.Fatalf("FileSystem() error = %v", err)
	}
	siteHandler, err := server.New(assets)
	if err != nil {
		t.Fatalf("server.New() error = %v; run the pinned frontend build before Go tests", err)
	}

	root := httptest.NewRecorder()
	siteHandler.ServeHTTP(root, edgeRequest(http.MethodGet, "/"))
	if root.Code != http.StatusOK {
		t.Fatalf("root status = %d", root.Code)
	}
	if got := root.Header().Get("Content-Type"); !strings.HasPrefix(got, "text/html") {
		t.Errorf("root Content-Type = %q", got)
	}
	if got := root.Header().Get("Cache-Control"); got != "no-cache" {
		t.Errorf("root Cache-Control = %q", got)
	}
	if etag := root.Header().Get("ETag"); !strongETag.MatchString(etag) {
		t.Errorf("root ETag = %q", etag)
	}
	for name, expected := range expectedOriginHeaders {
		if got := root.Header().Get(name); got != expected {
			t.Errorf("root %s = %q, want %q", name, got, expected)
		}
	}
	body := root.Body.String()
	// The data-static-fallback attribute is the structural contract for a
	// no-JavaScript first response. The fallback's copy is deliberately not
	// pinned: the temporary hello-world shell will become the real media-rich
	// site, and content is not an HTTP-boundary contract.
	if !strings.Contains(body, "data-static-fallback") {
		t.Fatalf("built root lacks the static application fallback marker: %q", body)
	}
	if strings.Contains(body, "/src/main.ts") {
		t.Fatalf("built root still references a development entrypoint: %q", body)
	}

	references := builtAssetReference.FindAllStringSubmatch(body, -1)
	if len(references) < 2 {
		t.Fatalf("built root has fewer than two generated asset references: %q", body)
	}
	referencedAssets := make(map[string]struct{}, len(references))
	for _, reference := range references {
		if !contentHashedAsset.MatchString(reference[1]) {
			t.Errorf("asset reference is not content-addressed: %s", reference[1])
		}
		referencedAssets[reference[1]] = struct{}{}
	}

	servedFiles := make(map[string]struct{})
	if err := fs.WalkDir(assets, ".", func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() || path == "index.html" || path == ".gitkeep" {
			return nil
		}
		if strings.HasPrefix(entry.Name(), ".") {
			t.Errorf("unexpected hidden embedded file: %s", path)
			return nil
		}

		publicPath := "/" + strings.TrimPrefix(path, "./")
		cacheControl := "no-cache"
		if strings.HasPrefix(publicPath, "/assets/") {
			if !contentHashedAsset.MatchString(publicPath) {
				t.Errorf("embedded immutable asset is not content-addressed: %s", publicPath)
			}
			cacheControl = "public, max-age=31536000, immutable"
		}
		servedFiles[publicPath] = struct{}{}
		assertServedFile(t, siteHandler, publicPath, cacheControl)
		return nil
	}); err != nil {
		t.Fatalf("walk embedded frontend: %v", err)
	}
	for reference := range referencedAssets {
		if _, found := servedFiles[reference]; !found {
			t.Errorf("index references an unembedded asset: %s", reference)
		}
	}

	rootHead := httptest.NewRecorder()
	siteHandler.ServeHTTP(rootHead, edgeRequest(http.MethodHead, "/"))
	if rootHead.Code != http.StatusOK || rootHead.Body.Len() != 0 {
		t.Errorf("HEAD / = status %d, %d bytes", rootHead.Code, rootHead.Body.Len())
	}
	if rootHead.Header().Get("ETag") != root.Header().Get("ETag") {
		t.Error("HEAD / ETag does not match GET")
	}

	placeholder := httptest.NewRecorder()
	siteHandler.ServeHTTP(placeholder, httptest.NewRequest(http.MethodGet, "/.gitkeep", nil))
	if placeholder.Code != http.StatusNotFound {
		t.Errorf("embedded .gitkeep status = %d", placeholder.Code)
	}
	for _, sourcePath := range []string{"/src/main.ts", "/assets/application.js.map"} {
		response := httptest.NewRecorder()
		siteHandler.ServeHTTP(response, httptest.NewRequest(http.MethodGet, sourcePath, nil))
		if response.Code != http.StatusNotFound {
			t.Errorf("source artifact %s status = %d", sourcePath, response.Code)
		}
	}
}

// faviconDeclaration reads the icon the built document actually asks a browser
// for, so the test below follows the document's own reference rather than a
// path restated here — a renamed file that nothing declares fails, and so does
// a declaration pointing at a file the bundle never embedded.
var faviconDeclaration = regexp.MustCompile(`<link rel="icon"[^>]*href="(/[^"]+)"`)

// browserIconTypes are the media types a browser will accept as a tab icon AND
// that Go resolves from its own BUILT-IN table, which is the only registry the
// distroless runtime image has: it carries no /etc/mime.types, so an extension
// outside that table is served application/octet-stream and, under the
// nosniff header this origin always sends, is refused as an icon. The list is
// stated here rather than derived from mime.TypeByExtension precisely so a
// development machine's richer registry cannot vouch for an extension
// production would fail on — ".ico" resolves to image/x-icon on macOS and to
// nothing at all in the container.
var browserIconTypes = map[string]struct{}{
	"image/svg+xml": {},
	"image/png":     {},
	"image/webp":    {},
	"image/gif":     {},
	"image/jpeg":    {},
	"image/avif":    {},
}

// TestBuiltFrontendServesTheDeclaredFavicon proves the tab mark is a promise
// the origin keeps (issue #239). Before it the site declared no icon at all,
// so every visit cost a WARN-level 404 for the /favicon.ico a browser probes
// when a document names none.
func TestBuiltFrontendServesTheDeclaredFavicon(t *testing.T) {
	assets, err := website.FileSystem()
	if err != nil {
		t.Fatalf("FileSystem() error = %v", err)
	}
	siteHandler, err := server.New(assets)
	if err != nil {
		t.Fatalf("server.New() error = %v; run the pinned frontend build before Go tests", err)
	}

	root := httptest.NewRecorder()
	siteHandler.ServeHTTP(root, edgeRequest(http.MethodGet, "/"))
	declared := faviconDeclaration.FindStringSubmatch(root.Body.String())
	if declared == nil {
		t.Fatalf("the built document declares no icon, so every visit is probed for /favicon.ico: %q", root.Body.String())
	}
	href := declared[1]

	icon := httptest.NewRecorder()
	siteHandler.ServeHTTP(icon, edgeRequest(http.MethodGet, href))
	if icon.Code != http.StatusOK {
		t.Fatalf("declared icon %s status = %d; the document names a file the bundle does not embed", href, icon.Code)
	}
	contentType, _, err := mime.ParseMediaType(icon.Header().Get("Content-Type"))
	if err != nil {
		t.Fatalf("declared icon %s Content-Type = %q: %v", href, icon.Header().Get("Content-Type"), err)
	}
	if _, ok := browserIconTypes[contentType]; !ok {
		t.Errorf(
			"declared icon %s is served %q; the runtime image has no MIME registry beyond Go's built-in table, so an extension outside it becomes application/octet-stream and nosniff refuses it as an icon",
			href, contentType,
		)
	}
	// A root-level bundle file: revalidated, never immutable — it carries no
	// content hash, so the operator replacing the mark must be able to publish
	// it under the same URL.
	assertServedFile(t, siteHandler, href, "no-cache")
}

// TestBuiltShellStatesItsOwnBootFailure proves the honest boot state survives
// the build and reaches the wire (issue #239). The failure it is for is the
// one where the entry module is asked for and never arrives, so the answer has
// to be in the bytes the origin already sent — nothing that runs later can
// help, which is also why the retry is a plain link rather than a control.
func TestBuiltShellStatesItsOwnBootFailure(t *testing.T) {
	assets, err := website.FileSystem()
	if err != nil {
		t.Fatalf("FileSystem() error = %v", err)
	}
	siteHandler, err := server.New(assets)
	if err != nil {
		t.Fatalf("server.New() error = %v; run the pinned frontend build before Go tests", err)
	}

	root := httptest.NewRecorder()
	siteHandler.ServeHTTP(root, edgeRequest(http.MethodGet, "/"))
	body := root.Body.String()
	// Structure, never copy: the markers are the contract, the words are the
	// owner's to change.
	for _, marker := range []string{"data-static-fallback", "data-boot-status", "data-boot-noscript"} {
		if !strings.Contains(body, marker) {
			t.Errorf("the served shell carries no %s; a visitor whose module never arrives reads a bare heading", marker)
		}
	}
	if !strings.Contains(body, `<a href="/">`) {
		t.Error("the served shell offers no scriptless retry; the visitor it is for has no working script to give them one")
	}
}
